name: Deploy to Render

on:
  push:
    branches:
      - dev # Déclenche le workflow sur la branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Vérifier le dépôt
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Étape 2 : Configurer Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Étape 3 : Connexion à DockerHub (facultatif, si vous poussez l'image vers DockerHub)
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Étape 4 : Construire l'image Docker
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/francoisdcre/emotionrecognizer:latest

    # Étape 5 : Déployer sur Render
    - name: Deploy to Render
      env:
        RENDER_TOKEN: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST "https://api.render.com/v1/services/srv-cu3a9ml2ng1s73c875f0/deploys" \
          -H "Authorization: Bearer $RENDER_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"clearCache": true}'
