name: Deploy to Render

on:
  push:
    branches:
      - dev  # Branche qui déclenche le workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          "https://api.render.com/v1/services/srv-cu3a9ml2ng1s73c875f0/deploys"
